import { Repository } from "./Repository";

export class User{
    public login:string;
    public id:number;
    public node_id:string;
    public avatar_url:string;
    public gravatar_id:string;
    public url:string;
    public html_url:string;
    public followers_url:string;
    public following_url:string;
    public gists_url:string;
    public starred_url:string;
    public subscriptions_url:string;
    public organizations_url:string;
    public repos_url:string;
    public events_url:string;
    public received_events_url:string;
    public type:string;
    public site_admin:boolean;
    public name:string;
    public company:string;
    public blog:string;
    public location:string;
    public email:string;
    public hireable:string;
    public bio:string;
    public twitter_username:string;
    public public_repos:number;
    public public_gists:number;
    public followers:number;
    public following:number;
    public created_at:Date;
    public updated_at:Date;    
    public repositories:Array<Repository>;

    constructor(){
        this.login = '';
        this.id = 0;
        this.node_id = '';
        this.avatar_url = '';
        this.gravatar_id = '';
        this.url = '';
        this.html_url = '';
        this.followers_url = '';
        this.following_url = '';
        this.gists_url = '';
        this.starred_url = '';
        this.subscriptions_url = '';
        this.organizations_url = '';
        this.repos_url = '';
        this.events_url = '';
        this.received_events_url = '';
        this.type = '';
        this.site_admin = false;
        this.name = '';
        this.company = '';
        this.blog = '';
        this.location = '';
        this.email = '';
        this.hireable = '';
        this.bio = '';
        this.twitter_username = '';
        this.public_repos = 0;
        this.public_gists = 0;
        this.followers = 0;
        this.following = 0;
        this.created_at = new Date();
        this.updated_at = new Date();
        this.repositories = [];
    }
}